
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gabriel
 */
public class MostrarArtista extends javax.swing.JFrame {

    /**
     * Creates new form MenuArtista
     */
    private MenuEventos2 me;
    private EspacioMunicipalCultural e1;
    private EspacioMunicipalCultural e2;
    private DefaultTableModel tabla;
    public MostrarArtista() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.e1 = e1;
        this.e2 = e2;
    }
    public MostrarArtista(EspacioMunicipalCultural e1, EspacioMunicipalCultural e2, int n) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.e1 = e1;
        this.e2 = e2;
        tabla = new DefaultTableModel();
        tabla.addColumn("Nombre");
        tabla.addColumn("Nacionalidad");
        tabla.addColumn("Edad");
        tabla.addColumn("Disciplina");
        if (n == 1) {
            String V[] = new String[4];
            V[0] = e1.getEvento0().getArtistas0().getNombre();
            V[1] = e1.getEvento0().getArtistas0().getNacionalidad();
            V[2] = e1.getEvento0().getArtistas0().getEdad() + "";
            V[3] = e1.getEvento0().getArtistas0().getDisciplina();
            tabla.addRow(V);
            V[0] = e1.getEvento0().getArtistas1().getNombre();
            V[1] = e1.getEvento0().getArtistas1().getNacionalidad();
            V[2] = e1.getEvento0().getArtistas1().getEdad() + "";
            V[3] = e1.getEvento0().getArtistas1().getDisciplina();
            tabla.addRow(V);
            jTable1.setModel(tabla);
        }
        if (n == 2) {
            String V[] = new String[4];
            V[0] = e1.getEvento1().getArtistas0().getNombre();
            V[1] = e1.getEvento1().getArtistas0().getNacionalidad();
            V[2] = e1.getEvento1().getArtistas0().getEdad() + "";
            V[3] = e1.getEvento1().getArtistas0().getDisciplina();
            tabla.addRow(V);
            V[0] = e1.getEvento1().getArtistas1().getNombre();
            V[1] = e1.getEvento1().getArtistas1().getNacionalidad();
            V[2] = e1.getEvento1().getArtistas1().getEdad() + "";
            V[3] = e1.getEvento1().getArtistas1().getDisciplina();
            tabla.addRow(V);
            jTable1.setModel(tabla);
        }
        if (n == 3) {
            String V[] = new String[4];
            V[0] = e2.getEvento0().getArtistas0().getNombre();
            V[1] = e2.getEvento0().getArtistas0().getNacionalidad();
            V[2] = e2.getEvento0().getArtistas0().getEdad() + "";
            V[3] = e2.getEvento0().getArtistas0().getDisciplina();
            tabla.addRow(V);
            jTable1.setModel(tabla);
        }
        if (n == 4) {
            String V[] = new String[4];
            V[0] = e2.getEvento1().getArtistas0().getNombre();
            V[1] = e2.getEvento1().getArtistas0().getNacionalidad();
            V[2] = e2.getEvento1().getArtistas0().getEdad() + "";
            V[3] = e2.getEvento1().getArtistas0().getDisciplina();
            tabla.addRow(V);
            jTable1.setModel(tabla);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Artistas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        me = new MenuEventos2(e1, e2);
        me.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarArtista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarArtista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarArtista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarArtista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarArtista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
