DECLARE
    CURSOR C_ARTICULOS IS
        SELECT A.ID_ARTICULO, A.TITULO
        FROM ARTICULO A
        ORDER BY A.TITULO;
        
    V_ID_ARTICULO ARTICULO.ID_ARTICULO%TYPE;
    V_TITULO ARTICULO.TITULO%TYPE;
    
    CURSOR C_AUTORES IS
        SELECT P.NOMBRE, P.APELLIDO, P.GENERO
        FROM PERSONA P, AUTOR AU, ESCRIBE E
        WHERE P.CI = AU.CI
        AND AU.CI = E.CI
        AND E.ID_ARTICULO = V_ID_ARTICULO
        ORDER BY P.APELLIDO;
    V_NOMBRE_PERSONA PERSONA.NOMBRE%TYPE;
    V_APELLIDO_PERSONA PERSONA.APELLIDO%TYPE;
    V_GENERO PERSONA.GENERO%TYPE;

    CURSOR C_JURADOS IS
        SELECT P.NOMBRE, P.APELLIDO, C.PUNTUACION
        FROM PERSONA P, JURADO J, CALIFICA C
        WHERE P.CI = J.CI
        AND J.CI = C.CI
        AND C.ID_ARTICULO = V_ID_ARTICULO
        ORDER BY P.APELLIDO;
    V_PUNTUACION CALIFICA.PUNTUACION%TYPE;

    V_PROMEDIO NUMBER;
    V_NUM_AUTORES NUMBER;
    V_ROW_COUNTER NUMBER := 0; 

BEGIN
    DBMS_OUTPUT.PUT_LINE('Articulos');
    DBMS_OUTPUT.PUT_LINE(' ');

    OPEN C_ARTICULOS;
    LOOP
        -- Obtener artículo
        FETCH C_ARTICULOS INTO V_ID_ARTICULO, V_TITULO;
        EXIT WHEN C_ARTICULOS%NOTFOUND;
        V_ROW_COUNTER := V_ROW_COUNTER + 1;
        
        SELECT NVL(AVG(C.PUNTUACION), 0) INTO V_PROMEDIO
        FROM CALIFICA C
        WHERE C.ID_ARTICULO = V_ID_ARTICULO;

        SELECT COUNT(*) INTO V_NUM_AUTORES
        FROM ESCRIBE E
        WHERE E.ID_ARTICULO = V_ID_ARTICULO;

        DBMS_OUTPUT.PUT_LINE(V_ROW_COUNTER || ' ' || V_TITULO || ' CantAutores: ' || V_NUM_AUTORES || ' Promedio Obt: ' || V_PROMEDIO);
        
        DBMS_OUTPUT.PUT_LINE('      A U T O R E S');
        OPEN C_AUTORES;
        LOOP
            FETCH C_AUTORES INTO V_NOMBRE_PERSONA, V_APELLIDO_PERSONA, V_GENERO;
            EXIT WHEN C_AUTORES%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('      ' || V_APELLIDO_PERSONA || ' ' || V_NOMBRE_PERSONA || ' ' || V_GENERO);
        END LOOP;
        CLOSE C_AUTORES;
        
        DBMS_OUTPUT.PUT_LINE('      J U R A D O S');
        OPEN C_JURADOS;
        LOOP
            FETCH C_JURADOS INTO V_NOMBRE_PERSONA, V_APELLIDO_PERSONA, V_PUNTUACION;
            EXIT WHEN C_JURADOS%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('      ' || V_APELLIDO_PERSONA || ' ' || V_NOMBRE_PERSONA || ' ' || NVL(V_PUNTUACION, 0));
        END LOOP;
        CLOSE C_JURADOS;

        DBMS_OUTPUT.PUT_LINE('');
    END LOOP;
    CLOSE C_ARTICULOS;
END;
